config/routes.rb
Rails.application.routes.draw do
  resources :cities
  root 'cities#home'
  resources :users
  resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :user
  validates_presence_of :name, :user_id
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
    validates_presence_of :email, :username, :password_digest
  has_many :cities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include CitiesHelper

  helper_method :current_user


  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:home]

  caches_action :index
  caches_action :show, expires_in: 600

  def index
    @cities = current_user.cities.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @weather = weather_get(@city.name)
  end

  # GET /cities/new
  def new
    @city = current_user.cities.new
    expire_action :action => :index
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = current_user.cities.new(city_params)
    created = weather_get(params[:city][:name])
    if created
      @city = current_user.cities.new(city_params)
      if @city.save
        expire_action :action => :index
        redirect_to cities_path, notice: "City added."
      else
        render :new
      end
    else
      redirect_to cities_path, notice: "City unavailable. Please try again."
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
    expire_action :action => :index
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_city
    @city = current_user.cities.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def city_params
    params.require(:city).permit(:user_id, :name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      login_user!(@user)
    else
      flash.now[:error] = "Invalid username or password"
      render :new
    end
  end
    def destroy
      session[:user_id] = nil
      flash[:notice] = "Logged out successfully"
      redirect_to root_path
    end

    def login_user!(user)
      session[:user_id] = @user.id
      flash[:notice] = "Welcome, you're now logged in"
      redirect_to cities_path
    end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    return render action: 'new' unless @user.save
    login_user!(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username,:password, :password_confirmation, :email)
  end

  def login_user!(user)
    session[:user_id] = @user.id
    flash[:notice] = "Welcome, you're now logged in"
    redirect_to cities_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
  def weather_get(city_name)
    HTTParty.get("http://api.openweathermap.org/data/2.5/weather?q=#{city_name}&units=imperial&APPID=#{ENV["OPENWEATHER_KEY"]}")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/_form.html.erb
<div class = "sign">
  <div class="login-wrap">
    <div class="login-html">
      <div class="login-form">


        <%= form_with(model: city, local: true) do |form| %>
        <% if city.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

          <ul>
            <% city.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <div class="group">
          <label for="user" class="label">City name or zip code</label>
          <%= form.text_field :name, id: :city_name, class: "input" %>
        </div>
        <div class="actions">
          <%= form.submit class: "button" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/home.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center text-primary">Search on the home page for the weather in one particular city, or sign in to create a profile with multiple cities</h3>
    <span id="error"></span>
  </div>

  <div class="row">
    <h3 class="text-center text-primary">Enter City Name</h3>
    <span id="error"></span>
  </div>

  <div class="row form-group form-inline" id="rowDiv">
    <input type="text" name="city" id="city", class="form-control" placeholder="City Name">
    <button id="submitWeather" class="btn btn-primary">Search City</button>
  </div>
</div>

<div id="show"></div>

app/views/cities/index.html.erb
<h1><center> <%= link_to 'Add a new city to your profile', new_city_path %></center></h1>



<% @cities.each do |city| %>

<div class="col-md-6">
  <div class="weather-card one ">

    <% if  weather_get(city.name).parsed_response['weather'][0]['main'].include? "Clouds" %>
    <div class="top-cloud">

      <% elsif  weather_get(city.name).parsed_response['weather'][0]['main'].include? "Thunderstorm" %>
      <div class="top-Thunderstorm">

        <% elsif  weather_get(city.name).parsed_response['weather'][0]['main'].include? "Drizzle" %>
        <div class="top-Drizzle">

          <% elsif  weather_get(city.name).parsed_response['weather'][0]['main'].include? "Rain" %>
          <div class="top-Rain">

            <% elsif  weather_get(city.name).parsed_response['weather'][0]['main'].include? "Snow" %>
            <div class="top-Snow">

              <% elsif  weather_get(city.name).parsed_response['weather'][0]['main'].include? "Atmosphere" %>
              <div class="top-Atmosphere">

                <% elsif  weather_get(city.name).parsed_response['weather'][0]['main'].include? "Clear" %>
                <div class="top-Clear">

                  <% elsif  weather_get(city.name).parsed_response['weather'][0]['main'].include? "Extreme" %>
                  <div class="top-Extreme">

                    <% elsif  weather_get(city.name).parsed_response['weather'][0]['main'].include? "Additional" %>
                    <div class="top-Additional">
      <% else %>
      <div class="top">
<% end %>
      <div class="wrapper">
        <div class="mynav">
          <%= link_to  city, method: :delete, data: { confirm: 'Are you sure?' } do  %>
          <span class="lnr lnr-cross-circle"></span>
          <% end %>
        </div>
        <h1 class="heading">Current Weather for <br>
          <%= weather_get(city.name).parsed_response['name'] %> ,
          <%= weather_get(city.name).parsed_response['sys']['country'] %></h1>
          <h3 class="location"></h3>
          <br>
          <br>
          <p class="temp">
            <span class="temp-value"><%= weather_get(city.name).parsed_response['main']['temp'].to_i %></span>
            <span class="deg">0</span>
            <a href="javascript:;"><span class="temp-type">F</span></a>
          </p>
          <br>
          <p class="temp">
            <span><h1 class="heading-2"><strong><%= weather_get(city.name).parsed_response['weather'][0]['main'] %></strong></h1></span>
          </p>
          <h1 class="heading-3"><%= link_to 'Show more information', city %></h1>
        </div>
      </div>
      <div class="bottom">
        <div class="wrapper">
          <ul class="forecast">
            <a href="javascript:;"><span class="lnr lnr-chevron-up go-up"></span></a>
            <li class="active">
              <span class="date">Max Temperature</span>
              <span class="lnr lnr-sun condition">
                <span class="temp"> <%= weather_get(city.name).parsed_response['main']['temp_max'] %>
                  <span class="deg">0</span><span class="temp-type">F</span></span>
                </span>
              </li>
              <li class="active">
                <span class="date">Min Temperature</span>
                <span class="lnr lnr-cloud condition">
                  <span class="temp"><%= weather_get(city.name).parsed_response['main']['temp_min'] %><span class="deg">0</span><span class="temp-type">F</span></span>
                </span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <% end if @cities.any? %>
  

app/views/cities/new.html.erb
<h1><center>New City</center></h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<h2 style=font-size:40px; font-weight: bold; class='text-center'> Current Weather for <%= @weather.parsed_response['name'] %> ,
<%= @weather.parsed_response['sys']['country'] %>

<h3><strong>Weather</strong>: <%= @weather.parsed_response['weather'][0]['main'] %> </h3>
<h3><strong>Description</strong>: <%= @weather.parsed_response['weather'][0]['description'] %> </h3>
<h3><strong>Temperature</strong>: <%= @weather.parsed_response['main']['temp'] %> </h3>
<h3><strong>Presure</strong>: <%= @weather.parsed_response['main']['pressure'] %> </h3>
<h3><strong>Humidity</strong>: <%= @weather.parsed_response['main']['humidity'] %> </h3>
<h3><strong>Low Temperature</strong>: <%= @weather.parsed_response['main']['temp_min'] %> </h3>
<h3><strong>Max Temperature</strong>: <%= @weather.parsed_response['main']['temp_max'] %> </h3>
<h3><strong>Wind Speed</strong>: <%= @weather.parsed_response['wind']['speed'] %> </h3>
<h3><strong>Wind Direction</strong>: <%= @weather.parsed_response['wind']['deg'] %> </h3>

<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>


<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weather</title>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Jason's Super Awesome Weather App </a>
        <a class="navbar-brand" > |</a> 
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">

          <a class="navbar-brand" href="/cities">Cities</a>
        </ul>
        <p class="navbar-text pull-right">
          <% if current_user %>
          Logged in as <strong><%= current_user.username %></strong><br>
          <%= link_to "Logout", logout_path  %>
          <% else %>
          <%= link_to "Sign up", signup_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", login_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </div>
    </div>
  </nav>

  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <!-- <script src="weather.js"></script> -->
</body>
</html>

app/views/users/new.html.erb
<div class = "sign">

<%= form_for User.new, url: '/login' do |f| %>

<div class="login-wrap">
    <div class="login-html">
        <input id="tab-1" type="radio" name="tab" class="sign-in"><label for="tab-1" class="tab">Sign In</label>
        <input id="tab-2" type="radio" name="tab" class="sign-up" checked><label for="tab-2" class="tab">Sign Up</label>
        <div class="login-form">
            <div class="sign-in-htm">
                <div class="group">
                    <label for="user" class="label">Username</label>
                    <!-- <input id="user" type="text" class="input" > -->
                    <%= f.text_field :username, class: "input"  %>
                </div>
                <div class="group">
                    <label for="pass" class="label">Password</label>
                    <!-- <input id="pass" type="password" class="input" data-type="password"> -->
                     <%= f.password_field :password, class: "input", :"data-type" => "password" %>
                </div>
                <div class="group">
                    <input id="check" type="checkbox" class="check" checked>
                    <label for="check"><span class="icon"></span> Keep me Signed in</label>
                </div>
                <div class="group">
                  <%= f.submit 'Sign In', class: "button" %>
                  <!-- <input type="submit" class="button" value="Sign Up"> -->
                </div>
                <div class="hr"></div>
                <div class= "foot-lnk">
                    <a href="#forgot"> Forgot Password?</a>
                </div>
            </div>

          <% end %>
<%= form_for :user, url: '/users' do |f| %>
<div class="sign-up-htm">
    <div class="group">
        <label for="user" class="label">Username</label>
        <!-- <input id="user" type="text" class="input" > -->
        <%= f.text_field :username, class: "input" %>
    </div>
    <div class="group">
        <label for="pass" class="label">Password</label>
        <!-- <input id="pass" type="password" class="input" data-type="password"> -->
        <%= f.password_field :password, class: "input", :"data-type" => "password"  %>
    </div>
    <div class="group">
        <label for="pass" class="label">Repeat Password</label>
        <!-- <input id="pass" type="password" class="input" data-type="password"> -->
        <%= f.password_field :password_confirmation, class: "input", :"data-type" => "password" %>
    </div>
    <div class="group">
        <label for="pass" class="label">Email Address</label>
        <!-- <input id="pass" type="text" class="input"> -->
        <%= f.text_field :email, class: "input" %>
    </div>
    <div class="group">
        <input type="submit" class="button" value="Sign Up">
    </div>
    <div class="hr"></div>
    <div class="foot-lnk">
        <label for="tab-1">Already Member?</a>
    </div>
</div>
<% end %>
</div>
</div>
</div>
</div>